version: '3'
services:
  producer:
    build:
      context: ./producer
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - rabbitmq
    networks:
      - my_network

  consumer:
    build:
      context: ./consumer
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq
    networks:
      - my_network

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=root
    networks:
      - my_network

networks:
  my_network:
    driver: bridge